/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuthenticationResponse } from '../models/authentication-response';
import { confirmAccount } from '../fn/authentication/confirm-account';
import { ConfirmAccount$Params } from '../fn/authentication/confirm-account';
import { login } from '../fn/authentication/login';
import { Login$Params } from '../fn/authentication/login';
import { refresh } from '../fn/authentication/refresh';
import { Refresh$Params } from '../fn/authentication/refresh';
import { register } from '../fn/authentication/register';
import { Register$Params } from '../fn/authentication/register';


/**
 * Authentication API
 */
@Injectable({ providedIn: 'root' })
export class AuthenticationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `register()` */
  static readonly RegisterPath = '/api/v1/auth/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `register()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  register$Response(params?: Register$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = register(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `register$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  register(params?: Register$Params, context?: HttpContext): Observable<void> {
    const resp = this.register$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `refresh()` */
  static readonly RefreshPath = '/api/v1/auth/refresh';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refresh()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refresh$Response(params: Refresh$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponse>> {
    const obs = refresh(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refresh$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refresh(params: Refresh$Params, context?: HttpContext): Observable<AuthenticationResponse> {
    const resp = this.refresh$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AuthenticationResponse>): AuthenticationResponse => r.body)
    );
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/api/v1/auth/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponse>> {
    const obs = login(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Observable<AuthenticationResponse> {
    const resp = this.login$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AuthenticationResponse>): AuthenticationResponse => r.body)
    );
  }

  /** Path part for operation `confirmAccount()` */
  static readonly ConfirmAccountPath = '/api/v1/auth/confirm-account';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `confirmAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  confirmAccount$Response(params: ConfirmAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = confirmAccount(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `confirmAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  confirmAccount(params: ConfirmAccount$Params, context?: HttpContext): Observable<void> {
    const resp = this.confirmAccount$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
