spring:
  application:
    name: Talksy-API
  config:
    import: optional:classpath:.env.properties
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: souhailamouri123@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB


app:
  security:
    jwt:
      access-token-expiration: 86400000 # 24 hours
      refresh-token-expiration: 604800000 # 7 days
      invitation-expiration: 900000 # 30 mins
    disposable-email: 10 Minute Mail, Temp Mail, Guerrilla Mail, Mailinator, Proton Mail (Temp), YOPmail, Dispostable, EmailOnDeck, Burner Mail, Temp-Mail.org, Internxt Temp Mail, AdGuard Temp Mail, 33 Mail, Spamgourmet, Mohmal
  mail:
    from-email: souhailamouri123@gmail.com
    frontend:
      activation-url: http://localhost:4200/activate-account*
  file:
    uploads:
      media-output-path: ./uploads

springdoc:
  default-produces-media-type: application/json

