/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageUpdateRequest } from '../../models/message-update-request';

export interface EditMessage$Params {
  'chat-id': number;
  'message-id': number;
      body: MessageUpdateRequest
}

export function editMessage(http: HttpClient, rootUrl: string, params: EditMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, editMessage.PATH, 'patch');
  if (params) {
    rb.path('chat-id', params['chat-id'], {});
    rb.path('message-id', params['message-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

editMessage.PATH = '/api/v1/messages/{chat-id}/{message-id}';
