/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponse {
  id?: number;
  lastMessage?: string;
  lastMessageTime?: string;
  name?: string;
  recipientId?: number;
  recipientOnline?: boolean;
  senderId?: number;
  unreadChatsCount?: number;
}
