/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponse {
  createdAt?: string;
  id?: number;
  media?: string;
  message?: string;
  recipientId?: number;
  senderId?: number;
  state?: 'SENT' | 'SEEN';
  type?: 'TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO' | 'VOICE';
}
