/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageRequest {
  chatId?: number;
  content?: string;
  messageType?: 'TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO' | 'VOICE';
  receiverId?: number;
  senderId?: number;
}
