/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  firstName?: string;
  id?: number;
  lastName?: string;
  lastSeen?: string;
  online?: boolean;
}
